refactor: change infra structure

diff --git a/apps/auth-service/Dockerfile b/apps/auth-service/Dockerfile
--- a/apps/auth-service/Dockerfile
+++ b/apps/auth-service/Dockerfile
@@ -1,14 +1,21 @@
 FROM node:18-alpine
 
-WORKDIR /usr/src/app
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-COPY package*.json ./
-RUN npm install
+COPY ./apps/auth-service/package.json ./apps/auth-service/yarn.lock* ./apps/auth-service/package-lock.json* ./apps/auth-service/pnpm-lock.yaml* ./
 
-COPY . .
+RUN \
+    if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; \
+    else echo 'Lockfile not found.' && exit 1; \
+    fi
 
-RUN npx prisma generate
+COPY ./apps/auth-service .
 
-EXPOSE 3000
+RUN npm run build
 
-CMD ["npx", "ts-node", "src/index.ts"]
+CMD ["npm", "start"]
+
+EXPOSE 3007
diff --git a/apps/inventory-service-pembelian/Dockerfile b/apps/inventory-service-pembelian/Dockerfile
--- a/apps/inventory-service-pembelian/Dockerfile
+++ b/apps/inventory-service-pembelian/Dockerfile
@@ -1,15 +1,23 @@
 FROM node:18-alpine
 
-WORKDIR /usr/src/app
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-COPY ./inventory-service-pembelian/package.json ./
-COPY ./inventory-service-pembelian/yarn.lock* ./inventory-service-pembelian/package-lock.json* ./inventory-service-pembelian/pnpm-lock.yaml* ./
-RUN npm install
+COPY ./apps/inventory-service-pembelian/package.json ./apps/inventory-service-pembelian/yarn.lock* ./apps/inventory-service-pembelian/package-lock.json* ./apps/inventory-service-pembelian/pnpm-lock.yaml* ./
 
-COPY ./inventory-service-pembelian .
+RUN \
+    if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; \
+    else echo 'Lockfile not found.' && exit 1; \
+    fi
 
+COPY ./apps/inventory-service-pembelian .
+
+# RUN npx prisma migrate dev
 RUN npx prisma generate
+RUN npm run build
 
-EXPOSE 3000
+CMD ["npm", "start"]
 
-CMD ["npx", "ts-node", "src/index.ts"]
+EXPOSE 3003
diff --git a/apps/user-service/Dockerfile b/apps/user-service/Dockerfile
--- a/apps/user-service/Dockerfile
+++ b/apps/user-service/Dockerfile
@@ -1,14 +1,23 @@
 FROM node:18-alpine
 
-WORKDIR /usr/src/app
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-COPY package*.json ./
-RUN npm install
+COPY ./apps/user-service/package.json ./apps/user-service/yarn.lock* ./apps/user-service/package-lock.json* ./apps/user-service/pnpm-lock.yaml* ./
 
-COPY . .
+RUN \
+    if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then npm i -g pnpm && pnpm i --frozen-lockfile; \
+    else echo 'Lockfile not found.' && exit 1; \
+    fi
 
+COPY ./apps/user-service .
+
+# RUN npx prisma migrate dev
 RUN npx prisma generate
+RUN npm run build
 
-EXPOSE 3000
+CMD ["npm", "start"]
 
-CMD ["npx", "ts-node", "src/index.ts"]
+EXPOSE 3006
